# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-13 14:38
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.utils.timezone
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('video_streamer', '0002_auto_20171013_0053'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fileinfo',
            name='file_path_way',
        ),
        migrations.AddField(
            model_name='fileinfo',
            name='video_file',
            field=models.FileField(default=django.utils.timezone.now, help_text="The file you wish to upload. Make sure that it's the correct format.", upload_to='media'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fileinfo',
            name='video_title',
            field=models.CharField(default=datetime.datetime(2017, 10, 13, 14, 38, 24, 50527, tzinfo=utc), max_length=200),
            preserve_default=False,
        ),
    ]
