# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-13 14:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video_streamer', '0003_auto_20171013_0938'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fileinfo',
            name='video_file',
            field=models.FileField(help_text="The file you wish to upload. Make sure that it's the correct format.", upload_to=''),
        ),
    ]
