# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-13 15:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video_streamer', '0004_auto_20171013_0941'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('video_title', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('video_file', models.FileField(help_text="The file you wish to upload. Make sure that it's the correct format.", upload_to='')),
            ],
        ),
        migrations.DeleteModel(
            name='FileInfo',
        ),
    ]
