# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-13 15:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video_streamer', '0005_auto_20171013_1018'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='video_type',
            field=models.IntegerField(choices=[(0, 'video/ogg'), (1, 'video/webm'), (2, 'video/mp4'), (3, 'video/flv')], default=1, help_text='The Video type'),
        ),
    ]
