# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-14 15:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video_streamer', '0007_auto_20171014_0953'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='vid',
            field=models.CharField(max_length=200, primary_key=True, serialize=False),
        ),
    ]
