# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-14 15:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video_streamer', '0009_auto_20171014_1013'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='vid',
            field=models.CharField(default=1, max_length=200, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='video',
            name='video_title',
            field=models.CharField(max_length=200),
        ),
    ]
